### ISSUE TITLE
Developers & Community Engagement

### ISSUE THREAD

**Issue by joshthegreatavenue** [blockstack/app-mining#182]
Based on the number of dApps we have in our ecosystem, I noticed there are less than 10-15% of developers engages with the community. For example, everyone in Telegram is familiar with developers like David (Mumble), Shankar (Habit app), Russ (PGeon), Jessica (DCasso), Abdou (Dmail), Walterion (Arcane App), Friedger (OI apps) and several more. Or in Slack, we have Dant (NoteRiot), Terje, Alex and several more too. No doubt these developers have added GREAT value to 

However, I find it hard to believe that apps that DO NOT ENGAGE with real users can somehow be more successful than those who did. (I am talking about apps that have close to zero engagement in Slack, Telegram, Mumble, Discord, Twitter, LinkedIn, Facebook, etc, I go through all social media every 1-2 days.) Not only that, when an issue arises with their dApps, community members often time cannot reach out to the developers came asking us for a solution, while this is supposed to be the responsibility of the developer, not us. 

I am actually questioning the legitimacy of TMUI on how they review our apps. I got feedback from a developer saying he/she got a complete ZERO from a TMUI user because of unable to log in ONCE while pDrive has several times more bug and issues (This is from Telegram user complaints, I even get frequent major bugs on pDrive.) 

I am proposing that community managers and evangelists SHOULD be able to provide scores to developers who actively engage with users. Even Satoshi engages with his users in the early days! 

open for ideas.

**Comment by wilsonbright** [comment]
If developers are reachable and take due action on time by fixing bugs reported by the community, it communicates confidence among the community that the app used is here to stay and not abandoned. I'm not sure how we can measure this. Maybe add a point to the Awario binary as a social reach. Currently, it is 5 and we can take it to 6. This could be measured within our community groups like Slack, Telegram, Discord. Updates could be features, blogs/articles, outreach, and testimonials. Maybe just a weekly interaction or bi-weekly is good. This also opens up visibility to apps that are constantly working and delivering value month after month. This will help in showing the community that app teams are growing and serious about it.

**Comment by hstove** [comment]
> This also opens up visibility to apps that are constantly working and delivering value month after month. This will help in showing the community that app teams are growing and serious about it.

This sounds exactly like the "release notes reviewer" the @jeffdomke is proposing. #174 

Maybe we could kill two birds with one stone here, and have at least one evangelist be a release notes reviewer. I think that could be a good thing.

**Comment by jeffdomke** [comment]
Hey @joshthegreatavenue. I agree, community engagement is valuable and should be rewarded. I'm not sure if that reward should map to the apps they build exactly, but maybe. I'm not understanding the proposal here? Is this a new reviewer? How does it work, what score does it generate, and who runs it? It is hard to review these proposals when that stuff isn't crystal clear. 🙏

**Comment by joshthegreatavenue** [comment]
The reviewer could be just Blockstack evangelists and community managers from Telegram. 
Here are the things I checked often :

1. DAPP Twitter
2. dApp developers on Slack
3. Telegram engagement 
4. Discord engagement 
5. Email engagement 

I have been receiving a lot of complaints from the community that these developers do not the support they needed when encountering issues. 

We can come out with a rating system based on those metrics above.

More engagement = Higher score
Low engagement = Lower score
No engagement = No score 

I do not believe founders that does not listen and talk to their users is more successful than those who does. Besides, developers engagement always provide assurance to the community that they are here to grow and stay.

**Comment by dantrevino** [comment]
@joshthegreatavenue some open questions that might solidify this a bit:
1. How would you measure "more engagement" vs "low engagement" by dapp devs?  What are the concrete things that you would measure?
2. Who are "community managers and evangelists"? (I'm gonna use CME)  How do you identify them? 
3. How many CMEs can "vote" or "score" each month? 1? 3? All?
4. How do new people become a CME and get representation in this group?  Is there some level of engagement required?  Running an ongoing meetup?
5. Conversely, how do you remove CMEs who become inactive?

**Comment by friedger** [comment]
Re: open TMUI videos, see #94 for discussion.

What prevents us to create a ranking base on this evaluation right now? Is it a question about money? There are app directory apps out already, adding a vote button shouldn't be difficult.

**Comment by babyrusa** [comment]
@joshthegreatavenue I think there should be a way to have a diversity of TMUI users, like people from different ages and from multiple professionals, since different apps serve completely different purposes. A young tester who never ran a website before wouldn't know what Runkod is used for. I think there should be a way to diversify testers. Additionally, it's completely unfair for dev when testers comment on a nonexisting feature of the app. 
Dev engagement is good but that's pretty hard to measure at least for the moment.

**Comment by talhasch** [comment]
Completely agree @babyrusa . As instance, since beginning Runkod hasn't gotten any negative feedback from professionals. But one of TMUI tester dropped a comment that contains "The site is unprofessional"

**Comment by joshthegreatavenue** [comment]
Just wanting to bring this up again.

**Comment by arinyguedes** [comment]
> I am actually questioning the legitimacy of TMUI on how they review our apps. I got feedback from a developer saying he/she got a complete ZERO from a TMUI user because of unable to log in ONCE while pDrive has several times more bug and issues (This is from Telegram user complaints, I even get frequent major bugs on pDrive.)

Hello Joshua,

I am the developer of pDrive and despite not talking a lot, I follow the channels and I talked with the guy that was reporting the bug.

It was related to the change on Gaia limit file and I have already fixed it. If you have any other bugs, please let me know. As you can see, there is work being done outside of public channels that you are not aware of. 

Not sure it would be fair to give a low score just because the person didn't chat on Slack, despite fixing bugs.

**Comment by jeffdomke** [comment]
A good portion of evangelists are also app builders. Is this essentially an app builder and community vote? Sorry for repeating myself but I'm still not understanding the proposal and who would execute such a vote? I think these are the same questions @dantrevino is asking.

**Comment by joshthegreatavenue** [comment]
- App or Bug issues respond by community members and developers engaging actively in return in any channels is counted as a single engagement. 
- Developers helping other developers that are building on Blockstack
- There is an evangelist head in Blockstack, he has the list for all evangelists, happy to get them to join this initiative. 
- The Evangelist that has zero engagement in any platform within 10 days will be deemed inactive.
- Tweet and replies, I noticed high ranking apps of this months is winning despite very low engagement on Twitter. This is extremely odd. (https://docs.blockstack.org/develop/app-reviewers.html : Not sure why active social handles of certain dApps are losing.) 
- People knowing your apps in the channels, the more people mentioned about your apps in Slack, Telegram, the higher your score will be.
- Developers that promote another Blockstack app will be given score too. 
- Any Evangelist or CMs that participated in the app mining CANNOT join the voting process. (Use Blocksurvey) 

I am personally disappointed with how app mining is run and how the winners are picked.
I have spoken to some of the developers and they are very disappointed on how the efforts of being engaging are put to waste.  Being active in all channel matters. We go out and promote your apps and answers question. So, I think Blockstack community members or evangelists should have a say on app votes. 

We MUST Reward developers that want our ecosystem to succeed. I am talking about developers that go OUT and promote Blockstack. 

For @arinyguedes  , I think you are missing the point here. TBH, I find it difficult to buy what you said. 

Here are the stats : 

- In the last 14 days, Slack has no mentioned of pDrive.
- The majority do not even know who you are as a developer, resulted in people being frustrated - when bug arises. 
- Your website has no social handles, yet, you gained a very high Awario score, winning number one several times. How do people even find your Twitter? 
- In the last 41 days, pDrive only has 5 mentions by 3 different people in Telegram.
- And, your Twitter, @pdrivestorage only has 2 followers. Only 2 Person ever tweeted about you. (https://twitter.com/search?q=%40pdrivestorage&src=typed_query&f=live) This DM is from this one guy here ( https://twitter.com/pDriveStorage/status/1194664336519815168 )
- Reddit? You have Zero presence and mentioned.
- No Instagram too.
- People only know you because you ranked number one in app.co/mining. 
- Despite everything, there is no method in reaching out to you at your website. No email, no support. 
- You are not even searchable on Product Hunt.

I do not know where did you get the Awario score because your competitor, (No offense) XorDrive should be ranking higher. XorDrive has everything from Instagram, Telegram, Reddit, Twitter (Higher engagement), talks to people in Mumble and Slack, never had an issue with XorDrive too.  Even Satoshi Nakamoto talks to people in the early days in his community.

**Comment by joshthegreatavenue** [comment]
Here is how Evangelist & Community Managers process will looked like.

Step by step process :

1. Request questionnaires from TMUI. 
2. The numbers of dApps are divided by the total numbers of evangelists and community managers. The divided number is the total numbers of app testing per member.
3. Let's say there is 300 apps and 15 total number of CMs and Evangelists, each participants will test 20 apps per month. 
4. 20 apps are chosen at random for each testers.
5. Our testers who are more familiar with Blockstack dApps can pinpoint flaws in the test as well. Plus, our testers understand the difference between single-use and multi-use apps, e.g XorDrive (Drag and drop file storage) vs Runkod (Developers tool for Blockstack). 
6. The same tester will NOT BE ABLE to review the same apps within 4 months window. 
7. The questionnaire from TMUI will be exported to Blocksurvey for internal testing among the CMs and Evangelists. 
8. The concluded results can then be added as a new reviewer score, I called it 'Blockstack Score'. TryMyUI and Awario is not a decentralized entity, so, no argument here. 

If evangelists wants to get paid for testing, will this be an option?

@dantrevino @jeffdomke

**Comment by louiseivan** [comment]
Thanks for raising this @joshthegreatavenue, really happy to see that someone is taking the initiative to strengthen our developer + community engagement. First, I'm still trying to grasp the whole proposal like @jeffdomke. Second, I believe we should check first with our Evangelists if they are willing to shoulder another workload w/in our community. I just want to let you know that evangelists that aren't app miners don't even have a stake w/in our ecosystem. Most of our active evangelists don't even own an STX and does it solely because of the mission.

**Comment by jeffdomke** [comment]
Early in the program we had an investor community reviewer (similar population of people) and failed because it wasn't objective or unbiased. The App Miners voted to close this reviewer. I'm wondering if this idea reintroduces those problems. Also worried because many of the evangelists are also app builders. How would you address this?

**Comment by joshthegreatavenue** [comment]
I think I have already mentioned, any evangelists or CMs who participated in the App Mining cannot be part of the Evaluation process. 
Can you pinpoint the issue of investor community reviewer so I can take a read?

**Comment by psgganesh** [comment]
@joshthegreatavenue I just stumbled upon this GitHub issue, we hear you. Now that our domain-name issues are sorted, we will definitely look into these and keep all updated soon...

**Comment by dantrevino** [comment]
> Early in the program we had an investor community reviewer (similar population of people) and failed because it wasn't objective or unbiased. The App Miners voted to close this reviewer. I'm wondering if this idea reintroduces those problems. Also worried because many of the evangelists are also app builders. How would you address this?

Respectfully disagree here.  That community was early investors, and *nothing* like the evangelist community.  The reason it was shutdown was due to apathy.  Nobody was voting.  That early investor community had no interest in participating, while the community evangelist team, by its very definition has an interest in participating.

**Comment by hstove** [comment]
@dantrevino I'd assume you're right that the evangelists would be more active. I would agree with Jeff that the evangelists could have bias, and you can see from this thread alone that some folks are only interested in the apps where they interact with the founders. I'm not even saying that's right or wrong, but it is a bias.

**Comment by jeffdomke** [comment]
@dantrevino apologies you're right. I was a bit reductionist and blunt, but I can expand a bit. 

My opinion about the original investor voting: 

Most unbiased investors didn't care. They often placed votes based on little information and then never revoted as new apps entered, or existing apps improved. A small minority voted based on self-serving incentives (that had nothing to do with app quality) to help an app they created or supported (knew the founders, etc). 

Problems I predict with an evangelist based voting group: 

– Voting behavior biased by people building apps/getting rewards. Evangelists who also build apps should be disqualified, correct?
– Voting behavior would be detached from app quality. 
– Who is an evangelist in this future? Are there hard criteria? Are we going to block all the app builders who now urgently want to become evangelists? Why would every app builder not become evangelists as fast as possible? 

I assume the best intentions. I also do trust our evangelists to kick the tires on apps. But the problems above seem clear to me. Happy to be wrong I just need more info please.
